language: scala

scala:
   - 2.10.6
   - 2.11.8
   - 2.12.0-RC2
   
jdk:
  - oraclejdk8
  - oraclejdk7
  
matrix:
  allow_failures:
  - scala: 2.12.0-RC2
  - jdk: oraclejdk7

script:
   - sbt ++$TRAVIS_SCALA_VERSION test
